// Generated by gencpp from file dynamixel_sdk_examples/GetMotorSensors.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETMOTORSENSORS_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETMOTORSENSORS_H

#include <ros/service_traits.h>


#include <dynamixel_sdk_examples/GetMotorSensorsRequest.h>
#include <dynamixel_sdk_examples/GetMotorSensorsResponse.h>


namespace dynamixel_sdk_examples
{

struct GetMotorSensors
{

typedef GetMotorSensorsRequest Request;
typedef GetMotorSensorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMotorSensors
} // namespace dynamixel_sdk_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_sdk_examples::GetMotorSensors > {
  static const char* value()
  {
    return "9d09fdbf53e24d372145a4f9997470e8";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensors&) { return value(); }
};

template<>
struct DataType< ::dynamixel_sdk_examples::GetMotorSensors > {
  static const char* value()
  {
    return "dynamixel_sdk_examples/GetMotorSensors";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensors&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetMotorSensorsRequest> should match
// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetMotorSensors >
template<>
struct MD5Sum< ::dynamixel_sdk_examples::GetMotorSensorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_sdk_examples::GetMotorSensors >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_sdk_examples::GetMotorSensorsRequest> should match
// service_traits::DataType< ::dynamixel_sdk_examples::GetMotorSensors >
template<>
struct DataType< ::dynamixel_sdk_examples::GetMotorSensorsRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_sdk_examples::GetMotorSensors >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetMotorSensorsResponse> should match
// service_traits::MD5Sum< ::dynamixel_sdk_examples::GetMotorSensors >
template<>
struct MD5Sum< ::dynamixel_sdk_examples::GetMotorSensorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_sdk_examples::GetMotorSensors >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_sdk_examples::GetMotorSensorsResponse> should match
// service_traits::DataType< ::dynamixel_sdk_examples::GetMotorSensors >
template<>
struct DataType< ::dynamixel_sdk_examples::GetMotorSensorsResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_sdk_examples::GetMotorSensors >::value();
  }
  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETMOTORSENSORS_H
