// Generated by gencpp from file dynamixel_sdk_examples/GetMotorSensorsResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETMOTORSENSORSRESPONSE_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETMOTORSENSORSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_sdk_examples
{
template <class ContainerAllocator>
struct GetMotorSensorsResponse_
{
  typedef GetMotorSensorsResponse_<ContainerAllocator> Type;

  GetMotorSensorsResponse_()
    : current(0)
    , voltage(0)
    , temperature(0)  {
    }
  GetMotorSensorsResponse_(const ContainerAllocator& _alloc)
    : current(0)
    , voltage(0)
    , temperature(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_type;
  _current_type current;

   typedef int32_t _voltage_type;
  _voltage_type voltage;

   typedef int32_t _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMotorSensorsResponse_

typedef ::dynamixel_sdk_examples::GetMotorSensorsResponse_<std::allocator<void> > GetMotorSensorsResponse;

typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetMotorSensorsResponse > GetMotorSensorsResponsePtr;
typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetMotorSensorsResponse const> GetMotorSensorsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current &&
    lhs.voltage == rhs.voltage &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_sdk_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6164de43a7bcebb9479ac7571546b1f8";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6164de43a7bcebb9ULL;
  static const uint64_t static_value2 = 0x479ac7571546b1f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_sdk_examples/GetMotorSensorsResponse";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 current\n"
"int32 voltage\n"
"int32 temperature\n"
"\n"
;
  }

  static const char* value(const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
      stream.next(m.voltage);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMotorSensorsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_sdk_examples::GetMotorSensorsResponse_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current);
    s << indent << "voltage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.voltage);
    s << indent << "temperature: ";
    Printer<int32_t>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETMOTORSENSORSRESPONSE_H
